In [1]:
print("Hello World")

Hello World


In [2]:
2+3

5

In [3]:
9-8

1

In [4]:
4*6

24

In [5]:
5/2

2.5

In [6]:
5//2

2

In [7]:
2**2

4

In [8]:
(8+2)*3

30

In [9]:
10%3

1

In [10]:
print('rahiman')

rahiman


In [11]:
'rahiman'

'rahiman'

In [12]:
"rahiman's laptop"

"rahiman's laptop"

In [13]:
10*'rahiman'

'rahimanrahimanrahimanrahimanrahimanrahimanrahimanrahimanrahimanrahiman'

In [14]:
print("c:docs\naved")

c:docs
aved


In [15]:
print(r'c:\docs\naved')

c:\docs\naved


In [16]:
x = 2

In [17]:
print(x)

2


In [18]:
x+3

5

In [19]:
y = 4
z = 8
print(y+z)

12


In [20]:
print(y)

4


In [21]:
name = 'rahiman'
print(name)

rahiman


In [22]:
name+' kodidela@gmail.com'

'rahiman kodidela@gmail.com'

In [23]:
name[0]

'r'

In [24]:
name[9]

IndexError: string index out of range

In [25]:
name[3:5]

'im'

In [26]:
name[:6]

'rahima'

In [27]:
name[3:]

'iman'

In [28]:
name[::-1]

'namihar'

In [29]:
name[0:5]

'rahim'

In [30]:
name[5:0]

''

In [31]:
name[-2]

'a'

In [32]:
name[0:3]='rahiman'

TypeError: 'str' object does not support item assignment

In [33]:
'kal'+name[0:3]

'kalrah'

In [34]:
nums = [25, 23, 36, 95, 14]
print(nums)

[25, 23, 36, 95, 14]


In [35]:
nums[4]

14

In [36]:
names = ['rahiman', 'koti', 'nagarjuna']
print(names)

['rahiman', 'koti', 'nagarjuna']


In [37]:
values = [9.5, 1112, 67]
print(values)

[9.5, 1112, 67]


In [38]:
mil = [names, values]

In [39]:
print(mil)

[['rahiman', 'koti', 'nagarjuna'], [9.5, 1112, 67]]


In [40]:
nums.append(45)

In [41]:
print(nums)

[25, 23, 36, 95, 14, 45]


In [42]:
nums.insert(2,1000000)

In [43]:
print(nums)

[25, 23, 1000000, 36, 95, 14, 45]


In [44]:
nums.remove(100000)

ValueError: list.remove(x): x not in list

In [45]:
nums.remove(1000000)

In [46]:
print(nums)

[25, 23, 36, 95, 14, 45]


In [47]:
nums.pop(2)

36

In [48]:
nums

[25, 23, 95, 14, 45]

In [49]:
del nums[1:]

In [50]:
nums

[25]

In [51]:
nums.extend([36, 95, 14, 45, 12])

In [52]:
nums

[25, 36, 95, 14, 45, 12]

In [53]:
min(nums)

12

In [54]:
max(nums)

95

In [55]:
nums.sort()

In [56]:
print(nums)

[12, 14, 25, 36, 45, 95]


In [57]:
tup = (21, 34, 67, 89)

In [58]:
print(tup)

(21, 34, 67, 89)


In [59]:
tup[1]

34

In [60]:
setts = {12, 34, 56, 78 ,90}

In [61]:
print(setts)

{34, 12, 78, 56, 90}


In [62]:
help()


Welcome to Python 3.8's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.8/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> 

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [63]:
num = 5
id(num)

1707976688

In [64]:
name = 'kodidela rahiman'

In [65]:
print(id(name))

109360480


In [66]:
a = 10
b = a
print(a)
print()
print(b)
print(id(a))
print()
print(id(b))

10

10
1707976768

1707976768


In [67]:
id(10)

1707976768

In [68]:
k = 10
a = 9
print(id(k))
print(id(a))

1707976768
1707976752


In [69]:
b = 123
print(id(b))

1707978576


In [70]:
print(id(10))

1707976768


In [71]:
pi = 3.14
print(pi)

3.14


In [72]:
type(pi)

float

In [73]:
num = 2
print(type(num))

<class 'int'>


In [74]:
num2 = 5.7
num3 = 7+9j
print(type(num2))
print(type(num3))

<class 'float'>
<class 'complex'>


In [75]:
a = 7.8
b = int(a)
print(a, type(a))
print(b, type(b))

7.8 <class 'float'>
7 <class 'int'>


In [76]:
k = float(b)
print(type(b))

<class 'int'>


In [77]:
k = 6
c = complex(b,k)
print(c, type(c))

(7+6j) <class 'complex'>


In [78]:
b<k

False

In [79]:
k>b

False

In [80]:
a<b

False

In [81]:
b<a

True

In [82]:
a=a

In [83]:
a

7.8

In [84]:
a==a

True

In [85]:
a!=a

False

In [86]:
int(True)

1

In [87]:
int(False)

0

In [88]:
num = [25, 46, 45 ,12]
type(num)

list

In [89]:
s = {25, 36 ,48, 12}
type(s)

set

In [90]:
t = ('rahia', 'nivetha')
type(t)

tuple

In [91]:
range(0,10)

range(0, 10)

In [92]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [93]:
set(range(0,10))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [94]:
tuple(range(100))

(0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99)

In [95]:
list(range(2, 12, 5))

[2, 7]

In [96]:
d = {'rahiman':'redmi','nag': '1plus', 'naved': 'iphone'}
print(type(d))

<class 'dict'>


In [97]:
d['rahiman']

'redmi'

In [98]:
d.get('rahiman')

'redmi'

In [99]:
d.keys()

dict_keys(['rahiman', 'nag', 'naved'])

In [100]:
d.values()

dict_values(['redmi', '1plus', 'iphone'])

In [101]:
x = 20
y = 36

In [102]:
x+y

56

In [103]:
x-y

-16

In [104]:
x*y

720

In [105]:
x/y

0.5555555555555556

In [106]:
x//y

0

In [107]:
x%y

20

In [108]:
x+=2

In [109]:
x

22

In [110]:
a,b = 5,6

In [111]:
print(b,a)

6 5


In [112]:
a<b

True

In [113]:
b<a

False

In [114]:
a==b

False

In [115]:
b==5

False

In [116]:
n=7
print(n)

7


In [117]:
-n

-7

In [118]:
n = -n

In [119]:
n

-7

In [120]:
a = 5

In [121]:
b = 4

In [122]:
a<8 and b<5

True

In [123]:
a<8 and b<2

False

In [124]:
x = True
print(x)

True


In [125]:
not x

False

In [126]:
x = not x
x

False

In [127]:
a = 5
b  = 6
print('before swapping')
print(a,b)
print()
temp = a
a = b
b = temp
print('after swapping')
print(a,b)

before swapping
5 6

after swapping
6 5


In [128]:
c = 13
d = 89
print('before swapping')
print(c,d)
print()
c = c+d
d = c-d
c = c-d
print('after swapping')
print(c,d)

before swapping
13 89

after swapping
89 13


In [129]:
a = 7
b = 4
print(a,b)
a,b=b,a
print()
print(a,b)

7 4

4 7


In [130]:
~12

-13

In [131]:
13<<12

53248

In [132]:
12&13

12

In [133]:
13&12

12

In [134]:
12|13

13

In [135]:
13|12

13

In [136]:
12^13

1

In [137]:
10<<12

40960

In [138]:
10<<2

40

In [139]:
25^30

7

In [140]:
25 & 30

24

In [141]:
import math
x = math.sqrt(25)
print(x)

5.0


In [142]:
from math import*
x = sqrt(64)
x

8.0

In [143]:
y = pow(8,2)

In [144]:
y

64.0

In [145]:
floor(2.9)

2

In [146]:
ceil(3.1)

4

In [147]:
pi

3.141592653589793

In [148]:
e

2.718281828459045

In [149]:
x = int(input('Enter a Number : '))
y = int(input('Enter a number : '))
print(x+y)

Enter a Number : 12
Enter a number : 13
25


In [150]:
x = 12
y = 12
if x == y:
    print("Correct")

Correct


In [151]:
i = 45
j = 65
if i == j:
    print("Equal")
else:
    print("Not Equal")

Not Equal


In [152]:
x = 12
y = 14
if x == y:
    print("Equals")
else:
    print("Not Equlas")

Not Equlas


In [153]:
x = 4
if x == 1:
    print("Day 1")
elif x == 2:
    print("Day 2")
elif x == 3:
    print("Day 3")
elif x == 4:
    print("Day 4")
else:
    print('Not Found')

Day 4


In [154]:
i = 0
while i<9:
    print('rahiman')
    i = i+1

rahiman
rahiman
rahiman
rahiman
rahiman
rahiman
rahiman
rahiman
rahiman


In [155]:
i = 0
while i<9:
    print('rahiman', i)
    i = i+1

rahiman 0
rahiman 1
rahiman 2
rahiman 3
rahiman 4
rahiman 5
rahiman 6
rahiman 7
rahiman 8


In [156]:
i = 5
while i >= 1:
    print('rahiman', i)
    i=i-1

rahiman 5
rahiman 4
rahiman 3
rahiman 2
rahiman 1


In [157]:
i = 0
while i<5:
    print('rahiman',i)
    i+=1

rahiman 0
rahiman 1
rahiman 2
rahiman 3
rahiman 4


In [158]:
i = 1
while i<=5:
    print('rahiman', end='')
    j = 1
    while j <=5:
        print(' rocks',end='' )
        j = j+1
    i=i+1
    print()

rahiman rocks rocks rocks rocks rocks
rahiman rocks rocks rocks rocks rocks
rahiman rocks rocks rocks rocks rocks
rahiman rocks rocks rocks rocks rocks
rahiman rocks rocks rocks rocks rocks


In [159]:
x = ['rahiman', 'naved', 'koti', 'chaithu', 'mujahid','nagarjuna']
for i in x:
    print(i)

rahiman
naved
koti
chaithu
mujahid
nagarjuna


In [160]:
print(x[2])

koti


In [161]:
for i in name:
    print(i)

k
o
d
i
d
e
l
a
 
r
a
h
i
m
a
n


In [162]:
for i in [2, 6, 'paul']:
    print(i)

2
6
paul


In [163]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [164]:
for i in range(11, 21, 2):
    print(i)

11
13
15
17
19


In [165]:
for i in range(1, 21):
    if i%5==0:
        print(i)

5
10
15
20


In [166]:
x = int(input('Enter no of chockies : '))
i = 0
while i<x:
    print('Chockies')
    i=i+1

Enter no of chockies : 5
Chockies
Chockies
Chockies
Chockies
Chockies


In [167]:
av = 5
x = int(input('Enter no of chockies : '))
i = 1
while i<x:
    if x>av:
        break
    print('canyds')
    i=i+1
print('bye')

Enter no of chockies : 8
bye


In [168]:
for i in range(1, 101):
    if i%3 == 0:
        continue
    print(i)

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
37
38
40
41
43
44
46
47
49
50
52
53
55
56
58
59
61
62
64
65
67
68
70
71
73
74
76
77
79
80
82
83
85
86
88
89
91
92
94
95
97
98
100


In [169]:
for i in range(1, 101):
    if i%3!= 0:
        pass
    else:
        print(i)
    

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57
60
63
66
69
72
75
78
81
84
87
90
93
96
99


In [170]:
for i in range(4):
    print('#')

#
#
#
#


In [171]:
for i in range(4):
    for j in range(i+1):
        print('# ', end='')
    print()

# 
# # 
# # # 
# # # # 


In [172]:
for i in range(4):
    for j in range(4-i):
        print('# ', end='')
    print()

# # # # 
# # # 
# # 
# 


In [173]:
nums = [12, 16, 15, 28, 25]
for num in nums:
    if num%5 == 0:
        print(num)

15
25


In [174]:
num = int(input("Enter Number : "))
if num > 1:
    for i in range(2, int(num/2)+1):
        if (num%i) == 0:
            print(num, "is not Prime")
            break
    else:
        print(num, "is Prime")
        
else:
    print(num, "is not prime")

Enter Number : 273
273 is not Prime


In [175]:
num = int(input())
for i in range(2,num):
    if num%i == 0:
        print("Not Prime")
        break
else:
    print("Prime")

5
Prime


In [176]:
import array
arr = array.array('i', [23, 45, 67, 89, 34])
print(arr)

array('i', [23, 45, 67, 89, 34])


In [177]:
print(arr.dtype)

AttributeError: 'array.array' object has no attribute 'dtype'

In [178]:
print(arr.type)

AttributeError: 'array.array' object has no attribute 'type'

In [179]:
print(type(arr))

<class 'array.array'>


In [180]:
from array import*
vals = array('i', [5, 9, -8, 4, 2])
print(vals.buffer_info())

(81495056, 5)


In [181]:
vals = array('i', [5, 9, -8, 4, 2])
print(vals.typecode)

i


In [182]:
vals = array('f', [5, 6, 4, 5.23, 56, 67])
vals.reverse()
print(vals)

array('f', [67.0, 56.0, 5.230000019073486, 4.0, 6.0, 5.0])


In [183]:
vals[3]

4.0

In [184]:
for i in range(5):
    print(vals[i])

67.0
56.0
5.230000019073486
4.0
6.0


In [185]:
for i in range(len(vals)):
    print(vals[i])

67.0
56.0
5.230000019073486
4.0
6.0
5.0


In [186]:
for e in vals:
    print(e)

67.0
56.0
5.230000019073486
4.0
6.0
5.0


In [187]:
from array import*
vals2 = array('f', [5, 3, 4, 23, 78])
new_arr = array(vals.typecode, (a for a in vals2) )
for e in new_arr:
    print(e)

5.0
3.0
4.0
23.0
78.0


In [188]:
new_arr = array(vals.typecode(a*a for a in vals2))
i = 0
while i<new_arr:
    print(new_arr[i])
    i = i+1

TypeError: 'str' object is not callable

In [189]:
from array import*
arrex = array('i',[])
n = int(input("Enter len of array : "))
for i in range(n):
    x = int(input("Enter values : "))
    arrex.append(x)
print(arrex)

Enter len of array : 


ValueError: invalid literal for int() with base 10: ''

In [190]:
print(arrex.index(int(input())))

ValueError: invalid literal for int() with base 10: ''

In [191]:
val = int(input())
print(arrex.index(val))

ValueError: invalid literal for int() with base 10: ''

In [192]:
val = int(input())
k = 0
for e in arrex:
    if e == val:
        print(k)
        break
    k = k+1

ValueError: invalid literal for int() with base 10: ''

In [ ]:
from numpy import*
arrnum = array([15,48,3,698,2,458,92,54])
print(arrnum)

In [193]:
print(arrnum.dtype)

NameError: name 'arrnum' is not defined

In [194]:
arrarray = array([1, 2, 3, 4, 5])
print(arr)

TypeError: array() argument 1 must be a unicode character, not list

In [195]:
print(arrarray.dtype)

NameError: name 'arrarray' is not defined

In [196]:
lins = linspace(0,15, 20)
print(lins)

NameError: name 'linspace' is not defined

In [197]:
lofs = logspace(1, 40, 12)

NameError: name 'logspace' is not defined

In [198]:
print(lofs)

NameError: name 'lofs' is not defined

In [199]:
aran = arange(1, 45, 12)
print(aran)

NameError: name 'arange' is not defined

In [200]:
ze = zeros(5)
print(ze)
print()
on = ones(6)
print(on)

NameError: name 'zeros' is not defined

In [201]:
arrcp1 = array([1,2,4,5,7,8])
arrcp2 = arrcp1 + 2
print(arrcp1)
print()
print(arrcp2)

TypeError: array() argument 1 must be a unicode character, not list

In [202]:
print(sin(arrcp1))

NameError: name 'arrcp1' is not defined

In [203]:
print(concatenate(arrcp1, arrcp2))

NameError: name 'concatenate' is not defined

In [204]:
print(arrcp1.concat(arrcp2))

NameError: name 'arrcp1' is not defined

In [205]:
import pandas

In [206]:
print(arrcp1.concat(arrcp2))

NameError: name 'arrcp1' is not defined

In [ ]:
from numpy import*
arr1con = array([1, 2 ,3, 4, 5])
arr2con = array([6, 7, 8, 9, 10])
print(concatenate([arr1con, arr2con]))

In [ ]:
arrcp3 = array([2, 6, 7, 8])
arr2 = arrcp3
print(arrcp3, id(arrcp3))
print()
print(arr2, id(arr2))

In [207]:
arrshcp1 = array([9, 8, 7, 6, 5])
arr2shcp2 = arrshcp1.view()
print(arrshcp1, id(arrshcp1))

TypeError: array() argument 1 must be a unicode character, not list

In [208]:
print(arr2shcp2, id(arr2shcp2))

NameError: name 'arr2shcp2' is not defined

In [209]:
arrshcp1[2] = 70
print(arrshcp1, id(arrshcp1))

NameError: name 'arrshcp1' is not defined

In [210]:
arrdpcp1 = array([65, 85, 72, 94, 34])
arrdpcp2 = arrdpcp1.copy()
print(arrdpcp1, id(arrdpcp1))
print()
print(arrdpcp2, id(arrdpcp2))

TypeError: array() argument 1 must be a unicode character, not list

In [ ]:
arrdpcp1[3] = 956
print(arrdpcp1, id(arrdpcp1))

In [211]:
print(arrdpcp2)

NameError: name 'arrdpcp2' is not defined

In [212]:
from numpy import*
arrmat = array(
[
    [1,2,3],
    [4,5,6]
])
print(arrmat)

[[1 2 3]
 [4 5 6]]


In [213]:
print(arrmat.ndim)

2


In [214]:
print(arrmat.dtype)

int32


In [215]:
print(arrmat.flatten())

[1 2 3 4 5 6]


In [216]:
print(arrmat)

[[1 2 3]
 [4 5 6]]


In [217]:
arrmatfl = arrmat.flatten()
print(arrmatfl)

[1 2 3 4 5 6]


In [218]:
arrmatres = arrmatfl.reshape(2, 3)
print(arrmatres)

[[1 2 3]
 [4 5 6]]


In [219]:
arrmat2 = array(
[
    [1, 2, 3, 4],
    [5,6,7,8]
])
m = matrix(arrmat2)
print(m)

[[1 2 3 4]
 [5 6 7 8]]


In [220]:
m2 = matrix(' 12 45 78 89; 45 89 56 23')
print(m2)

[[12 45 78 89]
 [45 89 56 23]]


In [221]:
print(diagonal(m2))

[12 89]


In [222]:
m1.min()

NameError: name 'm1' is not defined

In [223]:
m2.min()

12

In [224]:
m2.max()

89

In [225]:
m1 = m2+5

In [226]:
print(m1)

[[17 50 83 94]
 [50 94 61 28]]


In [227]:
m3 = m1*m2
m3

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [228]:
def greet():
    print('hello')


In [229]:
greet()

hello


In [230]:
def add(x, y):
    c = x+y
    print(c)

In [231]:
add(5,3)

8


In [232]:
def square(n):
    return n*n
res = square(int(input()))

ValueError: invalid literal for int() with base 10: ''

In [233]:
print(res)

NameError: name 'res' is not defined

In [234]:
def update(x):
    x = 8
    print(x)

In [235]:
update(10)

8


In [236]:
def update(x):
    x = 8
    print(x)
a = 10


In [237]:
update(a)

8


In [238]:
print(a)

10


In [239]:
id(x)


1707976736

In [240]:
id(a)

1707976768

In [241]:
def add(a, b):
    c = a+b
    print(c)
add(5, 6)

11


In [242]:
def person(name, age):
    print(name)
    print(age)
    

In [243]:
person('rahiman', 28)

rahiman
28


In [244]:
person(age = 21, name = 'kodidela rahiman')

kodidela rahiman
21


In [245]:
print(id(28))

1707977056


In [246]:
def persona(name, age = 18):
    print(name)
    print(age)
    

In [247]:
persona('KODIDELA RAHIMAN')

KODIDELA RAHIMAN
18


In [248]:
def sum(a, b):
    c = a+b
    print(c)

In [249]:
sum(4, 6)

10


In [250]:
sum(4, 5, 1)

TypeError: sum() takes 2 positional arguments but 3 were given

In [251]:
def sum(a, *b):
    c = a
    for i in b:
        c = c+i
    print(c)
    

In [252]:
sum(2, 3, 4)

9


In [253]:
def persona(name, *data):
    print(name)
    print(data)
    

In [254]:
persona('rahiman', 21, 8179311572)

rahiman
(21, 8179311572)


In [255]:
persona('rahiman', age = 21, phno = 8179311572)

TypeError: persona() got an unexpected keyword argument 'age'

In [256]:
def personals(name, **data):
    print(name)
    print(data)
    

In [257]:
personals('rahiman', age = 21, phno = 8179311572)

rahiman
{'age': 21, 'phno': 8179311572}


In [258]:
for i in personals:
    print(i)

TypeError: 'function' object is not iterable

In [259]:
def personals(name, **data):
    print(name)
    for i, j in data.items():
        print(i,j)

In [260]:
personals('rahiman', age = 21, phno = 8179311572)

rahiman
age 21
phno 8179311572


In [261]:
a = 10
print(a)

10


In [262]:
a = 10
def something():
    
    print(a)


In [263]:
print(a)

10


In [264]:
s = 12
print(id(s))
def so_mething():
    global s
    s = 25
    print(s)
    print(id(s))
so_mething()
print(s, id(s))

1707976800
25
1707977008
25 1707977008


In [265]:
a = 10

print(a, "id of global keyword", id(a))
def some_thing():
    a = 9
    x = globals()['a']
    print(id(x), a)
    
    globals()['a'] = 24
    print(id(a))
some_thing()
print("Global keyword", a)

10 id of global keyword 1707976768
1707976768 9
1707976752
Global keyword 24


In [266]:
def count(lst):
    even = 0
    odd = 0
    for i in lst:
        if i%2==0:
            even+=1
        else:
            odd+=1
    return even, odd

lst = [20, 25, 14, 19, 16, 24, 28, 41, 26]
even, odd = count(lst)
print("Even : {} and odd : {}".format(even, odd))

Even : 6 and odd : 3


In [267]:
def fibo(n):
    if n < 0:
        print("Try to learn how to get negative fiboanci in python")
    else:
        a = 0
        b = 1
        print(a)
        print(b)
        for i in range(2, n):
                c = a+b
                a = b
                b = c
                print(c)

In [268]:
fibo(-5)

Try to learn how to get negative fiboanci in python


In [269]:
def fact(n):
    f = 1
    for i in range(1, n+1):
        f = f*i
    return f
x = int(input())
result = fact(x)
print(result)

ValueError: invalid literal for int() with base 10: ''

In [270]:
def greet():
    print("Hello")
   
greet()

Hello


In [271]:
import sys
print(sys.getrecursionlimit())

3000


In [272]:
sys.setrecursionlimit(5000)
print(sys.getrecursionlimit())

5000


In [273]:
def fact(n):
    if n==0:
        return 1
    return n * fact(n-1)
result = fact(int(input()))

ValueError: invalid literal for int() with base 10: ''

In [274]:
print(result)

NameError: name 'result' is not defined

In [275]:
def sqaure(n):
    return n*n
res = square(int(input()))
print(res)

ValueError: invalid literal for int() with base 10: ''

In [ ]:
f = lambda a : a+a
result_of_lambda = f(4)
print(result_of_lambda)

In [276]:
def is_even(n):
    return n%2 == 0
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
evens = list(filter(is_even, nums))
print(evens)

[2, 4, 6, 8, 10]


In [277]:
nums = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
fl = list(filter(lambda n : n%2 == 0, nums))
print(fl)

[10, 12, 14, 16, 18, 20]


In [278]:
f2 = list(map(lambda n : n+20, fl)) 
print(f2)

[30, 32, 34, 36, 38, 40]


In [279]:
from functools import reduce
f3 = reduce(lambda a, b :  a+b, f2)

In [280]:
f3

210

In [281]:
def div(a,b):
    print(a/b)
div(4, 2)

2.0


In [282]:
div(2, 4)

0.5


In [283]:
def div(a, b):
    if a<b:
        a,b = b,a
    print(a/b)

In [284]:
div(4, 2)

2.0


In [285]:
div(2, 4)

2.0


In [286]:
import mod_telusuko_eg
a = 9
b = 7


ModuleNotFoundError: No module named 'mod_telusuko_eg'

In [287]:
class Computer:
    def __init__(self):
        print("in Init")
    def config(self):
        print("i5 8gb 1tb")
com1 = Computer()
com2 = Computer()
com1.config()
com2.config()

in Init
in Init
i5 8gb 1tb
i5 8gb 1tb


In [288]:
com1.Computer(config())

AttributeError: 'Computer' object has no attribute 'Computer'

In [289]:
Computer.config(com2)

i5 8gb 1tb
